### ISSUE TITLE
Code available？

### ISSUE THREAD

**Issue by ruiyuanlu** [mengyuest/AdaFuse#1]
Hi, this work is great. May I ask when will the code be available to reproduce results in your paper? Thanks.

**Comment by mengyuest** [comment]
We are working on it to get it released soon~

**Comment by iFLYTEK-Embodied-Robotics-Team** [comment]
Hi, this work is great. May I ask when will the code be available to reproduce results in your paper? Thanks.

**Comment by mengyuest** [comment]
I just updated the repo~
